########################################################################################################################
# Common section:
########################################################################################################################

########################################################################################################################
# windows-x86_64 platform:
########################################################################################################################

[windows-x86_64]
copy = []
link = []

[windows-x86_64.release]
copy = []
link = []

[windows-x86_64.debug]
copy = []
link = []

########################################################################################################################
# linux platform:
########################################################################################################################

[linux]
copy = [
            # ["mujoco/lib/libmujoco.so", "_build/$platform/$config/exts/omni.custom.physics/bin/"],
]
link = []

[linux.release]
copy = []
link = []

[linux.debug]
copy = []
link = []


########################################################################################################################
# linux-x86_64 platform:
########################################################################################################################

[linux-x86_64]
copy = []
link = []

[linux-x86_64.release]
copy = []
link = []

[linux-x86_64.debug]
copy = []
link = []

########################################################################################################################
# linux-arch64 platform:  todo
########################################################################################################################

[linux-aarch64]
copy = []
link = []

[linux-aarch64.release]
copy = []
link = []

[linux-aarch64.debug]
copy = []
link = []

########################################################################################################################
# Mac OS platform:
########################################################################################################################

[macos]
copy = []
link = []

[macos.release]
copy = []
link = []

[macos.debug]
copy = []
link = []
