########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

# Use the Kit Template repo configuration as a base. Only override things specific to the repo.
import_configs = ["${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml"]

# Repository Name
name = "kit-extension-template-cpp"

[repo_build.msbuild]
vs_version = "vs2019"

########################################################################################################################
# Build tool setup
########################################################################################################################

[repo_build]

# List of packman projects to pull (in order)
fetch.packman_host_files_to_pull = [
    "${root}/deps/host-deps.packman.xml",
]

fetch.packman_target_files_to_pull = [
    "${root}/deps/kit-sdk.packman.xml",
    "${root}/deps/omni-physics.packman.xml",
    "${root}/deps/target-deps.packman",
    "${root}/deps/ext-deps.packman.xml",
    "${root}/deps/repo-deps.packman.xml",
]

licensing.enabled = true
licensing.packages = [  "${root}/deps/target-deps.packman.xml" ]
licensing.fail_on_missing = true


[repo_docs]
name = "Kit Extension Template C++"
project = "kit-extension-template-cpp"
sphinx_exclude_patterns = [
    "_build",
    "tools",
    "VERSION.md",
    "source/extensions/*/docs/Overview.md",
    "source/extensions/*/docs/CHANGELOG.md",
]

[repo_docs.kit]
extensions = [
    "omni.example.cpp.actions",
    "omni.example.cpp.commands",
    "omni.example.cpp.hello_world",
    "omni.example.cpp.omnigraph_node",
    "omni.example.cpp.pybind",
    "omni.example.cpp.ui_widget",
    "omni.example.cpp.usd",
    "omni.example.cpp.usd_physics",
    "omni.example.python.hello_world",
    "omni.example.python.ui",
    "omni.custom.physics",
]

[repo_package.packages."platform:windows-x86_64".docs]
windows_max_path_length = 0
